[build]
  publish = "public"
  command = "pnpm run -w build --scope=labeilleviennoise.com --include-dependencies"
  # https://answers.netlify.com/t/support-guide-how-to-use-the-ignore-command/37517
  # ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- . ../../packages/"

[functions]
  node_bundler = "esbuild"
  included_files = ["./app/prisma-client/**/*", "!**/node_modules/.pnpm/@swc*/**/*", "!**/node_modules/.pnpm/typescript*/**/*"]

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
